name: Test Java Server Manager

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  test-java-server-manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install server manager package
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Set up Minecraft Server
        uses: yousefalshaikh17/minecraft-server-action@v1
        with:
          eula: 'true'
          properties: |
            rcon.password=${{ secrets.RCON_PASSWORD }}
            enable-rcon=true
            enable-query=true
            query.port=25574
          command: setup

      - name: Start Minecraft Server
        uses: yousefalshaikh17/minecraft-server-action@v1
        with:
          command: start

      - name: Run Python Tests
        run: |
          python tests/unit_tests.py

      - name: Stop Minecraft Server
        uses: yousefalshaikh17/minecraft-server-action@v1
        with:
          command: stop
